// export * from "./Specialty"
// export * from "./MedicalFacility"
// export * from "./OutstandingDoctor"
// export * from "./HandBook"
export { default as HandBook } from "./HandBook"
export { default as OutstandingDoctor } from "./OutstandingDoctor"
export { default as MedicalFacility } from "./MedicalFacility"
export { default as Specialty } from "./Specialty"
export { default as About } from "./About"
